### PR TITLE
Add artwork

### LINKED ISSUE #16: Add aesthetics
- [ ] Coin sprite
- [ ] Portal sprite
- [ ] Enemy sprite
- [ ] Player sprite

Try to maintain a nice flat look as we use in the https://github.com/GDquest/make-pro-2d-games-with-godot

Will the project have support for sfx and music @NathanLovato ? We can use mine to avoid spending time producing them and just focus on their implementation in this project we can use the ones from https://pigdev.itch.io/juans-saga 3rd place in music criterea in the JimJam btw :sunglasses:

### LINKED ISSUE #19: Remove Geometry2D.gd dependency
What `Geometry2D.gd` is out of scope for this little project. There's too many advanced concepts in there.

### PR DESCRIPTION
**Pull request by razcore-rad**
image

I've done the art in Inkscape & placed it in a root directory called `assets-raw`, at the same level as the `game` folder. I think the graphics are pretty nice, but let me know what you think anyway @henriiquecampos @NathanLovato 

closes #16 
closes #19

### CODE REVIEW

**Comment by razcore-rad** [comment]
In game screens:

image

image

image

**Comment by NathanLovato** [comment]
There's room to improve the harmony of the visuals, and to simplify them, improving the visuals overall:

- The portal has a complex look and it doesn't look like a door or a portal. It's not symbolic
- The coins look like balls, interactive orbs rather than collectibles, probably because they apply the same principles as the character style-wise
- There are detailed patterns on the character and coin the but the walls and the portal are plain
- The pure black for the background isn't an ideal shade
- The purple glow from the portal leaks around and doesn't look good right now imo.
- The grey-ish blue at the bottom of the background is muddy while the top of the gradient is close to the saturation of the characters

UI:

- Lacks value contrast between the buttons and the background

Characters:

- The enemy doesn't read well. It could well be a chest with this look and proportions

**Comment by NathanLovato** [comment]
In general, the patterns inside the interactive elements won't work if you don't apply that to the entire visual design. And I don't want that to happen as it just makes the visuals more time-consuming to produce to not add so much visual appeal, and it removes some clarity.

**Comment by razcore-rad** [comment]
Considering the very well pointed out above critique here's the in-game updated "artwork"

image
image
image

**Comment by NathanLovato** [comment]
Suggestions

Screenshot from 2019-09-05 12-01-11

**Comment by henriiquecampos** [comment]
So I also wanted to put my hands on that. I used as reference the designs from [the ARPG course](https://github.com/GDquest/make-pro-2d-games-with-godot). I loved the blueprint background provided in one of the #1 references, I think that we could have it as one of our Tileset tiles and use Tilemap for background, quickly setting up the game's framing and also provide a good in-game visual grid, for reference for tweaking values. I think that keeping it plain flat is easier to read, gradients, especially on background, are tricky on the eyes.

your-first-godot-game

I also made some variants for colors, and for the portals. Besides their name, they were designed to be simply the Level's goal, or "exit point", but actual portals look actually nice anyway, I'd go with them. As for the enemy, I liked @razcore-art approach to give a visual clue that their sides are dangerous, but I couldn't think of anything better than spikes, like his approach, so...I kept as the previous iteration, but I think we could work on it later, maybe not for this particular project, but for further ones.

your-first-godot-game-alts

If you like these tweaks, I can push them to this PR.

**Comment by NathanLovato** [comment]
The idea is good, flat colors would work. But:

- I prefer Razvan's idea of going for light outlines and darker fills as you get extra value contrast against the dark background
- For the color palette, I'd rather use an existing vibrant one, either a good pixel art palette or e.g. David Revoy's one. Right now the tones are inconsistent in terms of vibrance, with a fluorescent green, desaturated blue and teal for the character, and much more saturated portal from the previous assets. Also, we don't need color variations at this point.
- I also prefer the blueprint grid as a light tone, as blueprints are white lines over a vibrant blue background

**Comment by henriiquecampos** [comment]
The variant colors aren't a palette, at least not consciously, I just put some alternatives so we could pick one from them and take rid of the rest.

Based on your feedback I found a nice palette, [Pear36](https://lospec.com/palette-list/pear36) I just couldn't find a good color in that palette for the enemies, but overall this is how it turned out:

your-first-godot-game

I also made a darker variant:

your-first-godot-game-darker

My only problem with white grids is that I consistently feel that optical illusion that there are dots popping on their intersections.

**Comment by NathanLovato** [comment]
This is looking nice. For the grid, you can go with a much more subtle tone, you don't want to have too much contrast in the background anyway.

Regarding the palette, we can add a few colors, and use transparency e.g. on the grid.

**Comment by NathanLovato** [comment]
The upper version is nice, if you can just tone down the white lines, it's good to integrate in the game, push, and merge.

Note, there's no need for color variations for characters and what-not.

**Pull request merged**
