### PR TITLE
Porting to Godot 4

### PR DESCRIPTION
**Pull request by brno32**
**Please check if the PR fulfills these requirements:**

- [x] The commit message follows our guidelines.
- For bug fixes and features:
    - [x] You tested the changes.

Related issue (if applicable): #44 

# Info

Though we've discussed adding a new `godot4-game` folder, I'm opening this against the `game` folder so we can see the diff.

I was quite surprised at how large the diff is, but I guess godot 4 uses a much different metadata format for assets than godot 3, so I don't think there's a way around it. It might make sense to maybe only include the gdscript changes just so we can focus on the API changes for now. Any thoughts regarding this unwieldly diff?

### CODE REVIEW

**Comment by brno32** [comment]
@NathanLovato any thoughts?

**Comment by NathanLovato** [comment]
Sorry for the slow answer. This PR is on my to-do list, just that this list is a bit long at the moment. Having a big diff is completely fine, please don't worry about it.

I'll test and review this over the weekend. Thanks much for taking the time to port the demo!

**Comment by brno32** [comment]
Cool! No worries. In that case, I put everything under the `godot4-game` folder as discussed. Thanks!

**Comment by NathanLovato** [comment]
Thanks much for the work!

**Pull request merged**
